
Comment ( //////////AAR Type E Couplers\\\\\\\\\\ )


	Coupling (
		Type ( Automatic )
		Spring (
			Stiffness ( 1.1e6N/m 4.8e6N/m )
			Damping ( 1.1e6N/m/s 1.1e6N/m/s )
			Break ( 1.6e6N 1.6e6N )
			r0 ( 20cm 30cm )
		)
		Velocity ( 0.1m/s )
	)
	Coupling (
		Type ( Automatic )
		Spring (
			Stiffness ( 1.1e6N/m 4.8e6N/m )
			Damping ( 1.1e6N/m/s 1.1e6N/m/s )
			Break ( 1.6e6N 1.6e6N )
			r0 ( 20cm 30cm )
		)
		Velocity ( 0.1m/s )
	)
	Buffers (
		Spring (
			Stiffness ( 1e6N/m 5e6N/m )
			Damping ( 1.1e6N/m/s 1.1e6N/m/s )
			r0 ( 0m 1e9 )
		)
		Centre ( 0.5 )
		Radius ( 1 )
		Angle ( 0.5deg )
	)
